/*
 * Copyright (c) 2016, Freescale Semiconductor, Inc.
 * Copyright 2016-2017 ,2021 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v9.0
processor: MK66FN2M0xxx18
package_id: MK66FN2M0VMD18
mcu_data: ksdk2_0
processor_version: 9.0.0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_port.h"
#include "pin_mux.h"

#define PIN0_IDX                         0u   /*!< Pin number for pin 0 in a port */
#define PIN1_IDX                         1u   /*!< Pin number for pin 1 in a port */
#define PIN2_IDX                         2u   /*!< Pin number for pin 2 in a port */
#define PIN3_IDX                         3u   /*!< Pin number for pin 3 in a port */
#define PIN4_IDX                         4u   /*!< Pin number for pin 4 in a port */
#define PIN5_IDX                         5u   /*!< Pin number for pin 5 in a port */
#define PIN6_IDX                         6u   /*!< Pin number for pin 6 in a port */
#define PIN16_IDX                       16u   /*!< Pin number for pin 16 in a port */
#define PIN17_IDX                       17u   /*!< Pin number for pin 17 in a port */


/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: B11, peripheral: I2S0, signal: TXD0, pin_signal: ADC0_SE15/TSI0_CH14/PTC1/LLWU_P6/SPI0_PCS3/UART1_RTS_b/FTM0_CH0/FB_AD13/SDRAM_A21/I2S0_TXD0}
  - {pin_num: C8, peripheral: I2S0, signal: MCLK, pin_signal: CMP0_IN0/PTC6/LLWU_P10/SPI0_SOUT/PDB0_EXTRG/I2S0_RX_BCLK/FB_AD9/SDRAM_A17/I2S0_MCLK}
  - {pin_num: C7, peripheral: I2C1, signal: SCL, pin_signal: ADC1_SE6b/PTC10/I2C1_SCL/FTM3_CH6/I2S0_RX_FS/FB_AD5/SDRAM_A13, slew_rate: fast, open_drain: enable, pull_select: up,
    pull_enable: enable}
  - {pin_num: B7, peripheral: I2C1, signal: SDA, pin_signal: ADC1_SE7b/PTC11/LLWU_P11/I2C1_SDA/FTM3_CH7/I2S0_RXD1/FB_RW_b, slew_rate: fast, open_drain: enable, pull_select: up,
    pull_enable: enable}
  - {pin_num: G3, peripheral: I2S0, signal: TX_BCLK, pin_signal: PTE12/I2S0_TX_BCLK/FTM3_CH7}
  - {pin_num: G4, peripheral: I2S0, signal: TX_FS, pin_signal: PTE11/I2C3_SCL/I2S0_TX_FS/LPUART0_RTS_b/FTM3_CH6}
  - {pin_num: E10, peripheral: UART0, signal: RX, pin_signal: TSI0_CH9/PTB16/SPI1_SOUT/UART0_RX/FTM_CLKIN0/FB_AD17/SDRAM_D17/EWM_IN/TPM_CLKIN0}
  - {pin_num: E9, peripheral: UART0, signal: TX, pin_signal: TSI0_CH10/PTB17/SPI1_SIN/UART0_TX/FTM_CLKIN1/FB_AD16/SDRAM_D16/EWM_OUT_b/TPM_CLKIN1}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void)
{
    /* Port B Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortB);
    /* Port C Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortC);
    /* Port E Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortE);

    /* PORTB16 (pin E10) is configured as UART0_RX */
    PORT_SetPinMux(PORTB, 16U, kPORT_MuxAlt3);

    /* PORTB17 (pin E9) is configured as UART0_TX */
    PORT_SetPinMux(PORTB, 17U, kPORT_MuxAlt3);

    // sdcard
    const port_pin_config_t porte0_pin1_config = {
      kPORT_PullUp,                                            /* Internal pull-up resistor is enabled */
      kPORT_FastSlewRate,                                      /* Fast slew rate is configured */
      kPORT_PassiveFilterDisable,                              /* Passive filter is disabled */
      kPORT_OpenDrainDisable,                                  /* Open drain is disabled */
      kPORT_HighDriveStrength,                                 /* High drive strength is configured */
      kPORT_MuxAlt4,                                           /* Pin is configured as SDHC0_D1 */
      kPORT_UnlockRegister                                     /* Pin Control Register fields [15:0] are not locked */
    };
    PORT_SetPinConfig(PORTE, PIN0_IDX, &porte0_pin1_config);   /* PORTE0 (pin 1) is configured as SDHC0_D1 */
    const port_pin_config_t porte1_pin2_config = {
      kPORT_PullUp,                                            /* Internal pull-up resistor is enabled */
      kPORT_FastSlewRate,                                      /* Fast slew rate is configured */
      kPORT_PassiveFilterDisable,                              /* Passive filter is disabled */
      kPORT_OpenDrainDisable,                                  /* Open drain is disabled */
      kPORT_HighDriveStrength,                                 /* High drive strength is configured */
      kPORT_MuxAlt4,                                           /* Pin is configured as SDHC0_D0 */
      kPORT_UnlockRegister                                     /* Pin Control Register fields [15:0] are not locked */
    };
    PORT_SetPinConfig(PORTE, PIN1_IDX, &porte1_pin2_config);   /* PORTE1 (pin 2) is configured as SDHC0_D0 */
    const port_pin_config_t porte2_pin3_config = {
      kPORT_PullUp,                                            /* Internal pull-up resistor is enabled */
      kPORT_FastSlewRate,                                      /* Fast slew rate is configured */
      kPORT_PassiveFilterDisable,                              /* Passive filter is disabled */
      kPORT_OpenDrainDisable,                                  /* Open drain is disabled */
      kPORT_HighDriveStrength,                                 /* High drive strength is configured */
      kPORT_MuxAlt4,                                           /* Pin is configured as SDHC0_DCLK */
      kPORT_UnlockRegister                                     /* Pin Control Register fields [15:0] are not locked */
    };
    PORT_SetPinConfig(PORTE, PIN2_IDX, &porte2_pin3_config);   /* PORTE2 (pin 3) is configured as SDHC0_DCLK */
    const port_pin_config_t porte3_pin4_config = {
      kPORT_PullUp,                                            /* Internal pull-up resistor is enabled */
      kPORT_FastSlewRate,                                      /* Fast slew rate is configured */
      kPORT_PassiveFilterDisable,                              /* Passive filter is disabled */
      kPORT_OpenDrainDisable,                                  /* Open drain is disabled */
      kPORT_HighDriveStrength,                                 /* High drive strength is configured */
      kPORT_MuxAlt4,                                           /* Pin is configured as SDHC0_CMD */
      kPORT_UnlockRegister                                     /* Pin Control Register fields [15:0] are not locked */
    };
    PORT_SetPinConfig(PORTE, PIN3_IDX, &porte3_pin4_config);   /* PORTE3 (pin 4) is configured as SDHC0_CMD */
    const port_pin_config_t porte4_pin5_config = {
      kPORT_PullUp,                                            /* Internal pull-up resistor is enabled */
      kPORT_FastSlewRate,                                      /* Fast slew rate is configured */
      kPORT_PassiveFilterDisable,                              /* Passive filter is disabled */
      kPORT_OpenDrainDisable,                                  /* Open drain is disabled */
      kPORT_HighDriveStrength,                                 /* High drive strength is configured */
      kPORT_MuxAlt4,                                           /* Pin is configured as SDHC0_D3 */
      kPORT_UnlockRegister                                     /* Pin Control Register fields [15:0] are not locked */
    };
    PORT_SetPinConfig(PORTE, PIN4_IDX, &porte4_pin5_config);   /* PORTE4 (pin 5) is configured as SDHC0_D3 */
    const port_pin_config_t porte5_pin6_config = {
      kPORT_PullUp,                                            /* Internal pull-up resistor is enabled */
      kPORT_FastSlewRate,                                      /* Fast slew rate is configured */
      kPORT_PassiveFilterDisable,                              /* Passive filter is disabled */
      kPORT_OpenDrainDisable,                                  /* Open drain is disabled */
      kPORT_HighDriveStrength,                                 /* High drive strength is configured */
      kPORT_MuxAlt4,                                           /* Pin is configured as SDHC0_D2 */
      kPORT_UnlockRegister                                     /* Pin Control Register fields [15:0] are not locked */
    };
    PORT_SetPinConfig(PORTE, PIN5_IDX, &porte5_pin6_config);   /* PORTE5 (pin 6) is configured as SDHC0_D2 */
    const port_pin_config_t porte6_pin7_config = {
      kPORT_PullDown,                                          /* Internal pull-down resistor is enabled */
      kPORT_FastSlewRate,                                      /* Fast slew rate is configured */
      kPORT_PassiveFilterDisable,                              /* Passive filter is disabled */
      kPORT_OpenDrainDisable,                                  /* Open drain is disabled */
      kPORT_LowDriveStrength,                                  /* Low drive strength is configured */
      kPORT_MuxAsGpio,                                         /* Pin is configured as PTE6 */
      kPORT_UnlockRegister                                     /* Pin Control Register fields [15:0] are not locked */
    };
    PORT_SetPinConfig(PORTE, PIN6_IDX, &porte6_pin7_config);   /* PORTE6 (pin 7) is configured as PTE6 */

    // sai

    const port_pin_config_t portc10_pinC7_config = {/* Internal pull-up resistor is enabled */
                                                    kPORT_PullUp,
                                                    /* Fast slew rate is configured */
                                                    kPORT_FastSlewRate,
                                                    /* Passive filter is disabled */
                                                    kPORT_PassiveFilterDisable,
                                                    /* Open drain is enabled */
                                                    kPORT_OpenDrainEnable,
                                                    /* Low drive strength is configured */
                                                    kPORT_LowDriveStrength,
                                                    /* Pin is configured as I2C1_SCL */
                                                    kPORT_MuxAlt2,
                                                    /* Pin Control Register fields [15:0] are not locked */
                                                    kPORT_UnlockRegister};
    /* PORTC10 (pin C7) is configured as I2C1_SCL */
    PORT_SetPinConfig(PORTE, 24U, &portc10_pinC7_config); //!!!

    const port_pin_config_t portc11_pinB7_config = {/* Internal pull-up resistor is enabled */
                                                    kPORT_PullUp,
                                                    /* Fast slew rate is configured */
                                                    kPORT_FastSlewRate,
                                                    /* Passive filter is disabled */
                                                    kPORT_PassiveFilterDisable,
                                                    /* Open drain is enabled */
                                                    kPORT_OpenDrainEnable,
                                                    /* Low drive strength is configured */
                                                    kPORT_LowDriveStrength,
                                                    /* Pin is configured as I2C1_SDA */
                                                    kPORT_MuxAlt2,
                                                    /* Pin Control Register fields [15:0] are not locked */
                                                    kPORT_UnlockRegister};
    /* PORTC11 (pin B7) is configured as I2C1_SDA */
    PORT_SetPinConfig(PORTE, 25U, &portc11_pinB7_config); //!!!

    /* PORTC1 (pin B11) is configured as I2S0_TXD0 */ // 1
    PORT_SetPinMux(PORTC, 1U, kPORT_MuxAlt6);

    /* PORTC6 (pin C8) is configured as I2S0_MCLK */ // 2
    PORT_SetPinMux(PORTC, 8U, kPORT_MuxAlt4);

    /* PORTE11 (pin G4) is configured as I2S0_TX_FS */ // 3
    PORT_SetPinMux(PORTB, 19U, kPORT_MuxAlt4);

    /* PORTE12 (pin G3) is configured as I2S0_TX_BCLK */ // 4
    PORT_SetPinMux(PORTB, 18U, kPORT_MuxAlt4);

    /* PORTC7 is configured as I2S0_RX_FS */ // 5
	PORT_SetPinMux(PORTC, 7U, kPORT_MuxAlt4);

    /* PORTC9 is configured as I2S0_RX_BLK */ // 6
	PORT_SetPinMux(PORTC, 9U, kPORT_MuxAlt4);

    /* PORTC5 is configured as I2S0_RX_D0 */ // 7
	PORT_SetPinMux(PORTC, 5U, kPORT_MuxAlt4);


    // !!! start
    /* PORTE24 (pin 31) is configured as I2C0_SCL */
       PORT_SetPinMux(PORTE, 24U, kPORT_MuxAlt5);

       /* PORTE25 (pin 32) is configured as I2C0_SDA */
       PORT_SetPinMux(PORTE, 25U, kPORT_MuxAlt5);

       /* Port E Clock Gate Control: Clock enabled */
       CLOCK_EnableClock(kCLOCK_PortE);

       const port_pin_config_t porte24_pin31_config = {/* Internal pull-up resistor is enabled */
                                                       kPORT_PullUp,
                                                       /* Fast slew rate is configured */
                                                       kPORT_FastSlewRate,
                                                       /* Passive filter is disabled */
                                                       kPORT_PassiveFilterDisable,
                                                       /* Open drain is enabled */
                                                       kPORT_OpenDrainEnable,
                                                       /* Low drive strength is configured */
                                                       kPORT_LowDriveStrength,
                                                       /* Pin is configured as I2C0_SCL */
                                                       kPORT_MuxAlt5,
                                                       /* Pin Control Register fields [15:0] are not locked */
                                                       kPORT_UnlockRegister};
       /* PORTE24 (pin 31) is configured as I2C0_SCL */
       PORT_SetPinConfig(PORTE, 24U, &porte24_pin31_config);

       const port_pin_config_t porte25_pin32_config = {/* Internal pull-up resistor is enabled */
                                                       kPORT_PullUp,
                                                       /* Fast slew rate is configured */
                                                       kPORT_FastSlewRate,
                                                       /* Passive filter is disabled */
                                                       kPORT_PassiveFilterDisable,
                                                       /* Open drain is enabled */
                                                       kPORT_OpenDrainEnable,
                                                       /* Low drive strength is configured */
                                                       kPORT_LowDriveStrength,
                                                       /* Pin is configured as I2C0_SDA */
                                                       kPORT_MuxAlt5,
                                                       /* Pin Control Register fields [15:0] are not locked */
                                                       kPORT_UnlockRegister};
       /* PORTE25 (pin 32) is configured as I2C0_SDA */
       PORT_SetPinConfig(PORTE, 25U, &porte25_pin32_config);

    // !!! end
    SIM->SOPT5 = ((SIM->SOPT5 &
                   /* Mask bits to zero which are setting */
                   (~(SIM_SOPT5_UART0TXSRC_MASK)))

                  /* UART 0 transmit data source select: UART0_TX pin. */
                  | SIM_SOPT5_UART0TXSRC(SOPT5_UART0TXSRC_UART_TX));
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
